CSect	Symbol	Value	LENGTH	Flags:
--------------------------------------
COPY		000000	00107E
	FIRST		000000	R
	COPY		000000	R
	CLOOP		000003	R
	ENDFIL		000015	R
	RDREC		000027	R
	RLOOP		000034	R
	EXIT		00004C	R
	WRREC		000052	R
	WLOOP		000058	R
	RETADR		00006D	R
	LENGTH		000070	R
	INPUT		000073	R
	BUFFER		000078	R
	BUFEND		001078	R
	MAXLEN		00107B	R

Literal		Hex		Address		Length:
-------------------------------------------------------
EOF		454F46		0007		3
05		05		000A		1
